version: "3.9"

services:
  food_retail_app:
    build: .
    container_name: food_retail_app
    ports:
      - "10000:10000"
    env_file:
      - .env
    depends_on:
      food_retail_db:
        condition: service_healthy
    networks:
      - food_retail_net
    restart: unless-stopped

  food_retail_db:
    image: mysql:8
    container_name: food_retail_db
    env_file:
      - .env
    ports:
    - "3306:3306"
    volumes:
      - food_retail_db_data:/var/lib/mysql
    networks:
      - food_retail_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  food_retail_db_data:

networks:
  food_retail_net:
    driver: bridge
